- # Numpy from scratch

In [1]:
import numpy as np

## Datatypes in numpy

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- str - string
- f - float
- m - timedelta
- M - datetime
- O - object
- u - unsigned integer
- c - complex float
- U - unicode string
- V - fixed chunk of memory for other type ( void )

## How to creat numpy array 

desc

- start -> int
- stop  -> int
- step  -> int
- shape -> (2,3) or 2
- order -> int
- M     -> int
- N     -> int
- k     -> int


In [2]:
a=np.array([12,3,4,5])
a

array([12,  3,  4,  5])

In [3]:
a1=np.arange(1,11)     # arange(start,stop,step,dtype,like=None)
a2=np.arange(10)
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [4]:
a=np.empty((2,2))     #empty(shape,dtype,order,like)
a

array([[0.00000000e+000, 1.43400853e-311],
       [1.43400853e-311, 1.43400853e-311]])

In [5]:
a=np.ones(10,)     #ones(shape,dtype,order,like)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
a=np.zeros((5,5))  # zerosones(shape,dtype,order,like)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a=np.eye(2,2)    #eye(N,M,k,dtype,order)
a

array([[1., 0.],
       [0., 1.]])

In [8]:
a=np.random.randint(1,11,size=(3,4))
a

array([[6, 1, 2, 5],
       [6, 6, 7, 1],
       [5, 8, 9, 3]], dtype=int32)

## Attributes of ndarray

In [9]:
a1=np.array([1,2,3,4,5])
a2=np.array([[1,2],[3,4]])

In [10]:
type(a1)

numpy.ndarray

In [11]:
print(a1.shape)
print(a2.shape)

(5,)
(2, 2)


In [12]:
print(a1.ndim)
print(a2.ndim)

1
2


In [13]:
print(a1.dtype)
print(a2.dtype)

int64
int64


In [14]:
print(a1.itemsize)
print(a2.itemsize)

8
8


# Indexing , Sylicing & Updating

In [15]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([[1,2],[3,4]])

### indexing

In [16]:
a[0]

np.int64(1)

In [17]:
b[0]

array([1, 2])

In [18]:
b[1][0]
b[1,1]

np.int64(4)

- accesing multiple valuse

In [19]:
b[[1,0],[0,0]]

array([3, 1])

- indexing using boolen valuse

In [20]:
arr = np.random.randint(100, size = (10, ))
arr

array([ 5, 59, 14, 24,  9, 57, 22, 76, 47, 77], dtype=int32)

In [21]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[ 5 57 47 77]


### Slycing

In [22]:
a[:3]

array([1, 2, 3])

In [23]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

-

In [26]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [27]:
arr[0:2][2:]

array([], shape=(0, 4), dtype=int64)

In [28]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

### Updating

In [29]:
arr = np.random.randint(100, size = (5, 4))
print(arr)

[[24 89 81 55]
 [29 78 27 76]
 [46 95 71 45]
 [15 36 73 64]
 [83 62 69 63]]


In [30]:
arr[1,1]=99
print("Updated Array: \n", arr)

Updated Array: 
 [[24 89 81 55]
 [29 99 27 76]
 [46 95 71 45]
 [15 36 73 64]
 [83 62 69 63]]


# Flatten & Ravel

In [31]:

a=np.random.randint(1,11,size=(3,4))
a

array([[10,  4,  5,  8],
       [ 4, 10,  7,  9],
       [ 8,  8,  5,  3]], dtype=int32)

In [32]:
a.flatten()

array([10,  4,  5,  8,  4, 10,  7,  9,  8,  8,  5,  3], dtype=int32)

In [33]:
a.ravel()  #faster than flatten

array([10,  4,  5,  8,  4, 10,  7,  9,  8,  8,  5,  3], dtype=int32)

# Reshaping Array

In [34]:
a=np.random.randint(1,11,size=(3,4))
a

array([[ 5,  6,  3,  6],
       [ 7,  9,  8,  4],
       [ 5, 10,  1,  2]], dtype=int32)

In [35]:
a.reshape(4,3)

array([[ 5,  6,  3],
       [ 6,  7,  9],
       [ 8,  4,  5],
       [10,  1,  2]], dtype=int32)

In [36]:
a.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

# Itrator of Array 

` 1D array `

In [39]:
a=a.reshape(12,)
a

array([ 5,  6,  3,  6,  7,  9,  8,  4,  5, 10,  1,  2], dtype=int32)

In [40]:
for i in a:
    print(i,end=",")

5,6,3,6,7,9,8,4,5,10,1,2,

` 2D array `

In [47]:
a=a.reshape(4,3)

In [48]:
for i in a:
    print(i,end=" || ")

[5 6 3] || [6 7 9] || [8 4 5] || [10  1  2] || 

- using ` nditer ` || ` ravel ` || ` flatten `

In [52]:
for i in np.nditer(a):
    print(i,end=",")


5,6,3,6,7,9,8,4,5,10,1,2,