- # Numpy from scratch

In [1]:
import numpy as np

## Datatypes in numpy

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- str - string
- f - float
- m - timedelta
- M - datetime
- O - object
- u - unsigned integer
- c - complex float
- U - unicode string
- V - fixed chunk of memory for other type ( void )

## How to creat numpy array 

desc

- start -> int
- stop  -> int
- step  -> int
- shape -> (2,3) or 2
- order -> int
- M     -> int
- N     -> int
- k     -> int


In [2]:
a=np.array([12,3,4,5])
a

array([12,  3,  4,  5])

In [3]:
a1=np.arange(1,11)     # arange(start,stop,step,dtype,like=None)
a2=np.arange(10)
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [4]:
a=np.empty((2,2))     #empty(shape,dtype,order,like)
a

array([[2.12199579e-314, 4.67296746e-307],
       [7.13430793e-321, 6.34476742e-312]])

In [5]:
a=np.ones(10,)     #ones(shape,dtype,order,like)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
a=np.zeros((5,5))  # zerosones(shape,dtype,order,like)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a=np.eye(2,2)    #eye(N,M,k,dtype,order)
a

array([[1., 0.],
       [0., 1.]])

In [8]:
a=np.random.randint(1,11,size=(3,4))
a

array([[10,  1,  6,  8],
       [ 3,  6,  7,  8],
       [ 4,  5, 10,  4]], dtype=int32)

## Attributes of ndarray

In [9]:
a1=np.array([1,2,3,4,5])
a2=np.array([[1,2],[3,4]])

In [10]:
type(a1)

numpy.ndarray

In [11]:
print(a1.shape)
print(a2.shape)

(5,)
(2, 2)


In [12]:
print(a1.ndim)
print(a2.ndim)

1
2


In [13]:
print(a1.dtype)
print(a2.dtype)

int64
int64


In [14]:
print(a1.itemsize)
print(a2.itemsize)

8
8


# Indexing , Sylicing & Updating

In [15]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([[1,2],[3,4]])

### indexing

In [16]:
a[0]

np.int64(1)

In [17]:
b[0]

array([1, 2])

In [18]:
b[1][0]
b[1,1]

np.int64(4)

- accesing multiple valuse

In [19]:
b[[1,0],[0,0]]

array([3, 1])

- indexing using boolen valuse

In [20]:
arr = np.random.randint(100, size = (10, ))
arr

array([17, 26, 54, 34, 68, 59, 54, 63, 93, 47], dtype=int32)

In [21]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[17 59 93 47]


### Slycing

In [22]:
a[:3]

array([1, 2, 3])

In [23]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

-

In [26]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [27]:
arr[0:2][2:]

array([], shape=(0, 4), dtype=int64)

In [28]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

### Updating

In [29]:
arr = np.random.randint(100, size = (5, 4))
print(arr)

[[44 15 78 54]
 [91 27  5 94]
 [61 16 43  8]
 [17 88 25 63]
 [ 6 36 61 34]]


In [30]:
arr[1,1]=99
print("Updated Array: \n", arr)

Updated Array: 
 [[44 15 78 54]
 [91 99  5 94]
 [61 16 43  8]
 [17 88 25 63]
 [ 6 36 61 34]]


# Flatten & Ravel

In [31]:

a=np.random.randint(1,11,size=(3,4))
a

array([[5, 8, 4, 3],
       [3, 2, 5, 4],
       [2, 8, 9, 2]], dtype=int32)

In [32]:
a.flatten()

array([5, 8, 4, 3, 3, 2, 5, 4, 2, 8, 9, 2], dtype=int32)

In [33]:
a.ravel()  #faster than flatten

array([5, 8, 4, 3, 3, 2, 5, 4, 2, 8, 9, 2], dtype=int32)

# Reshaping Array

In [34]:
a=np.random.randint(1,11,size=(3,4))
a

array([[10,  7,  1,  1],
       [ 5, 10,  7,  2],
       [ 3,  8,  9,  4]], dtype=int32)

In [35]:
a.reshape(4,3)

array([[10,  7,  1],
       [ 1,  5, 10],
       [ 7,  2,  3],
       [ 8,  9,  4]], dtype=int32)

In [36]:
#a.reshape(3,3)

# Itrator of Array 

` 1D array `

In [37]:
a=a.reshape(12,)
a

array([10,  7,  1,  1,  5, 10,  7,  2,  3,  8,  9,  4], dtype=int32)

In [38]:
for i in a:
    print(i,end=",")

10,7,1,1,5,10,7,2,3,8,9,4,

` 2D array `

In [39]:
a=a.reshape(4,3)

In [40]:
for i in a:
    print(i,end=" || ")

[10  7  1] || [ 1  5 10] || [7 2 3] || [8 9 4] || 

- using ` nditer ` || ` ravel ` || ` flatten `

In [41]:
for i in np.nditer(a):
    print(i,end=",")


10,7,1,1,5,10,7,2,3,8,9,4,

# Operators in numpy

- `+`
- `-`
- `*`
- `/`
- `//`
- `%`
- `>`
- `<`
- `==`
- `<=`
- `>=`

In [42]:
a=np.random.randint(1,11,size=(2,2))
b=np.random.randint(1,11,size=(2,2))
a

array([[2, 2],
       [4, 2]], dtype=int32)

In [43]:
a+5

array([[7, 7],
       [9, 7]], dtype=int32)

In [44]:
a,b

(array([[2, 2],
        [4, 2]], dtype=int32),
 array([[5, 1],
        [4, 7]], dtype=int32))

In [45]:
a-1

array([[1, 1],
       [3, 1]], dtype=int32)

In [46]:
a-b

array([[-3,  1],
       [ 0, -5]], dtype=int32)

In [47]:
a/2

array([[1., 1.],
       [2., 1.]])

In [48]:
a//2

array([[1, 1],
       [2, 1]], dtype=int32)

In [49]:
a%2

array([[0, 0],
       [0, 0]], dtype=int32)

In [50]:
a==a

array([[ True,  True],
       [ True,  True]])

In [51]:
b

array([[5, 1],
       [4, 7]], dtype=int32)

In [52]:
a=np.random.randint(1,11,size=(2,2))
a

array([[5, 7],
       [8, 9]], dtype=int32)

In [53]:
a>b

array([[False,  True],
       [ True,  True]])

In [54]:
a*b

array([[25,  7],
       [32, 63]], dtype=int32)

In [55]:
a*2

array([[10, 14],
       [16, 18]], dtype=int32)

# numpy for Maths

In [56]:
a,b

(array([[5, 7],
        [8, 9]], dtype=int32),
 array([[5, 1],
        [4, 7]], dtype=int32))

In [57]:
np.add(a,b)

array([[10,  8],
       [12, 16]], dtype=int32)

In [58]:
np.subtract(a,b)

array([[0, 6],
       [4, 2]], dtype=int32)

In [59]:
a-b

array([[0, 6],
       [4, 2]], dtype=int32)

`tignometric`


In [60]:
a

array([[5, 7],
       [8, 9]], dtype=int32)

In [61]:
np.sqrt(4),np.sqrt(a)

(np.float64(2.0),
 array([[2.23606798, 2.64575131],
        [2.82842712, 3.        ]]))

In [62]:
np.sin(a),np.sin(1)

(array([[-0.95892427,  0.6569866 ],
        [ 0.98935825,  0.41211849]]),
 np.float64(0.8414709848078965))

In [63]:
np.cos(0)

np.float64(1.0)

In [64]:
np.exp(0)

np.float64(1.0)

`Matrix multiplication`

In [65]:
a,b

(array([[5, 7],
        [8, 9]], dtype=int32),
 array([[5, 1],
        [4, 7]], dtype=int32))

In [66]:
np.dot(a,b) # 1. way

array([[53, 54],
       [76, 71]], dtype=int32)

In [67]:
np.matmul(a,b) # 2.way

array([[53, 54],
       [76, 71]], dtype=int32)

In [68]:
a@b        #3. way

array([[53, 54],
       [76, 71]], dtype=int32)

`diagonal elements`

In [69]:
a=np.random.randint(1,11,size=(3,3))
a

array([[4, 1, 2],
       [5, 3, 3],
       [7, 6, 1]], dtype=int32)

In [70]:
np.diag(a)

array([4, 3, 1], dtype=int32)

`transpose`

In [71]:
a.T

array([[4, 5, 7],
       [1, 3, 6],
       [2, 3, 1]], dtype=int32)

# numpy for Static

In [72]:
x = np.array([[1,2], [3,4]])
print("Array: \n", x)
print("Sum: ", np.sum(x))
print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise
print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [[1 2]
 [3 4]]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [73]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: \n", x)
print("Minimum: ", np.min(x))
print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise
print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [74]:
x = np.array([160, 180, 146, 162, 184, 180])
print("Array: \n", x)
print("Minimum: ", np.min(x))
print("Maximum: ", np.max(x))
print("Mean: ", np.mean(x))
print("Median: ", np.median(x))
print("Variance: ", np.var(x))
print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [75]:
heights = np.array([160, 180, 146, 162, 184, 180])
weights = np.array([50, 78, 45, 51, 80, 60])
a=np.corrcoef(heights, weights)
a

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

# numpy extra

In [76]:
for i in (np.linspace(1, 5, 9)):
    print(i)

1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0


In [77]:
print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


`vStack`  &  `hStack`

In [78]:
a=np.array([[1,2],[3,4]])
b=np.array([[9,8],[7,6]])
b,a

(array([[9, 8],
        [7, 6]]),
 array([[1, 2],
        [3, 4]]))

In [79]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

In [80]:
np.hstack([a,b])

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])

In [81]:
np.concatenate([a,b],axis=1)

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])

- where
```python
numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)  
```

In [82]:
np.where(arr > 64, 0, 1)

array([[1, 1, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

In [83]:
arr


array([[44, 15, 78, 54],
       [91, 99,  5, 94],
       [61, 16, 43,  8],
       [17, 88, 25, 63],
       [ 6, 36, 61, 34]], dtype=int32)