* # Numpy from scratch

In [1]:
import numpy as np

## How to creat numpy array 

In [2]:
a=np.array([12,3,4,5])
a

array([12,  3,  4,  5])

In [3]:
a1=np.arange(1,11)
a2=np.arange(10)
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [4]:
a=np.ones(10,)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
a=np.eye(2,2)
a

array([[1., 0.],
       [0., 1.]])

## Attributes of ndarray

In [7]:
a1=np.array([1,2,3,4,5])
a2=np.array([[1,2],[3,4]])

In [8]:
type(a1)

numpy.ndarray

In [9]:
print(a1.shape)
print(a2.shape)

(5,)
(2, 2)


In [10]:
print(a1.ndim)
print(a2.ndim)

1
2


In [11]:
print(a1.dtype)
print(a2.dtype)

int32
int32


In [13]:
print(a1.itemsize)
print(a2.itemsize) 

4
4
